Ext.namespace("com.test.cmp");
com.test.cmp.UserDetailWindow=Ext.extend(Ext.Window,{
	title:'客户详情',
	width:400,
	height:300,
	closeAction:'hide',
	dataObj:{},
	initComponent:function(config){
		com.test.cmp.UserDetailWindow.superclass.initComponent.call(this);
	},
	setData:function(obj){
		this.dataObj=obj;
	}
});
Ext.reg("userdetailwindow",com.test.cmp.UserDetailWindow)